name: Release

on:
  release:
    types: [created]

jobs:
  build_and_upload_reproducible:
    name: Build and Upload Reproducible Contract
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to upload assets to release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.15.0/cargo-near-installer.sh | sh

      - name: Build Reproducible WASM
        run: ./build_all

      - name: Upload VeNEAR WASM to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./res/release/venear_contract.wasm
          asset_name: venear_contract.wasm
          asset_content_type: application/wasm
      - name: Upload Voting WASM to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./res/release/voting_contract.wasm
          asset_name: voting_contract.wasm
          asset_content_type: application/wasm
      - name: Upload lockup WASM to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./res/release/lockup_contract.wasm
          asset_name: lockup_contract.wasm
          asset_content_type: application/wasm

